### ISSUE TITLE
bseqsc, cdseq, cpm and momf fail with latest Docker image on provided test data

### ISSUE THREAD

**Issue by SciLiciumTheo** [omnideconv/deconvBench#40]
Hi,

I am running the Nextflow pipeline as explained [here](https://github.com/omnideconv/deconvBench/tree/main/pipeline#quickstart), with the latest Docker image (pulled on 2025-04-01). 

The only modifications I made to the `nextflow.config` file are input/output directories and general benchmarking parameters:
```
  data_dir_bulk = "/home/sciliciumtheo/omnideconv_bench/data/bulks/"                                                     // absolute path to directory that contains RNA-seq datasets
  data_dir_sc = "/home/sciliciumtheo/omnideconv_bench/data/single_cell/"                                                 // absolute path to directory that contains scRNA-seq datasets


  /*** output directories ***/  
  results_dir_general = "/home/sciliciumtheo/omnideconv_bench/test_results_fail"                                                     // absolute path to directory in which final results of the main and subsampling workflow are stored
  preProcess_dir = "/home/sciliciumtheo/omnideconv_bench/tmp"                                              // absolute path to directory in which temporary files are stored
  

  /*** Benchmarking Parameters [general] ***/  
  single_cell_list = ["sc1"]                                                                    // list of scRNA-seq dataset names that will be used for deconvolution. 
  bulk_list = ["bulk1","bulk2"]                                                                 // list of RNA-seq dataset names that will be used for deconvolution. 
  method_list = ["bseqsc", "cdseq", "cpm", "momf"]
```

Any method of `bseqsc`, `cdseq`, `cpm` and `momf` (added to `nextflow.config`) fail with similar error (here for `cpm`):

```
ERROR ~ Error executing process > 'CREATE_SIGNATURE (2)'

Caused by:
  Process `CREATE_SIGNATURE (2)` terminated with an error exit status (1)


Command executed:

  computeSignaturesNF.R 'sc1' '/home/sciliciumtheo/omnideconv_bench/data/single_cell/' 'bulk2' '/home/sciliciumtheo/omnideconv_bench/data/bulks/' 'cpm' '/home/sciliciumtheo/omnideconv_bench/test_results_fail_cpm' 'false' '0' '0' '4' '/home/sciliciumtheo/omnideconv_bench/pipeline'

Command exit status:
  1

Command output:
  [1] "Starting signature building script ..."
  R version 4.4.0 (2024-04-24)
  Platform: x86_64-pc-linux-gnu
  Running under: Ubuntu 20.04.6 LTS

  Matrix products: default
  BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
  LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3;  LAPACK version 3.9.0

  locale:
  [1] C

  time zone: Etc/UTC
  tzcode source: system (glibc)

  attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods   base

  other attached packages:
  [1] omnideconv_0.0.0.9000 snowfall_1.84-6.3     snow_0.4-4

  loaded via a namespace (and not attached):
   [1] Matrix_1.7-0        gtable_0.3.6        jsonlite_1.8.9
   [4] dplyr_1.1.4         compiler_4.4.0      Rcpp_1.0.14
   [7] tidyselect_1.2.1    Biobase_2.62.0      parallel_4.4.0
  [10] tidyr_1.3.1         png_0.1-8           scales_1.3.0
  [13] fastmap_1.2.0       lattice_0.22-6      reticulate_1.40.0
  [16] ggplot2_3.5.1       R6_2.5.1            generics_0.1.3
  [19] BiocGenerics_0.48.1 htmlwidgets_1.6.4   tibble_3.2.1
  [22] munsell_0.5.1       pillar_1.10.1       RColorBrewer_1.1-3
  [25] rlang_1.1.5         lazyeval_0.2.2      viridisLite_0.4.2
  [28] plotly_4.10.4       cli_3.6.3           withr_3.0.2
  [31] magrittr_2.0.3      digest_0.6.37       grid_4.4.0
  [34] rappdirs_0.3.3      lifecycle_1.0.4     vctrs_0.6.5
  [37] glue_1.8.0          data.table_1.16.4   colorspace_2.1-1
  [40] purrr_1.0.4         httr_1.4.7          tools_4.4.0
  [43] pkgconfig_2.0.3     htmltools_0.5.8.1
  python:         /root/.local/share/r-miniconda/envs/r-omnideconv/bin/python
  libpython:      /root/.local/share/r-miniconda/envs/r-omnideconv/lib/libpython3.10.so
  pythonhome:     /root/.local/share/r-miniconda/envs/r-omnideconv:/root/.local/share/r-miniconda/envs/r-omnideconv
  version:        3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
  numpy:          /root/.local/share/r-miniconda/envs/r-omnideconv/lib/python3.10/site-packages/numpy
  numpy_version:  1.26.4

  NOTE: Python version was forced by use_python() function
  [1] "Method: cpm; sc-norm: ; bulk-norm: "

Command error:
  Loading required package: snowfall
  Loading required package: snow
  Skipping python installation checks ...
  R version 4.4.0 (2024-04-24)
  Platform: x86_64-pc-linux-gnu
  Running under: Ubuntu 20.04.6 LTS

  Matrix products: default
  BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
  LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3;  LAPACK version 3.9.0

  locale:
  [1] C

  time zone: Etc/UTC
  tzcode source: system (glibc)

  attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods   base

  other attached packages:
  [1] omnideconv_0.0.0.9000 snowfall_1.84-6.3     snow_0.4-4

  loaded via a namespace (and not attached):
   [1] Matrix_1.7-0        gtable_0.3.6        jsonlite_1.8.9
   [4] dplyr_1.1.4         compiler_4.4.0      Rcpp_1.0.14
   [7] tidyselect_1.2.1    Biobase_2.62.0      parallel_4.4.0
  [10] tidyr_1.3.1         png_0.1-8           scales_1.3.0
  [13] fastmap_1.2.0       lattice_0.22-6      reticulate_1.40.0
  [16] ggplot2_3.5.1       R6_2.5.1            generics_0.1.3
  [19] BiocGenerics_0.48.1 htmlwidgets_1.6.4   tibble_3.2.1
  [22] munsell_0.5.1       pillar_1.10.1       RColorBrewer_1.1-3
  [25] rlang_1.1.5         lazyeval_0.2.2      viridisLite_0.4.2
  [28] plotly_4.10.4       cli_3.6.3           withr_3.0.2
  [31] magrittr_2.0.3      digest_0.6.37       grid_4.4.0
  [34] rappdirs_0.3.3      lifecycle_1.0.4     vctrs_0.6.5
  [37] glue_1.8.0          data.table_1.16.4   colorspace_2.1-1
  [40] purrr_1.0.4         httr_1.4.7          tools_4.4.0
  [43] pkgconfig_2.0.3     htmltools_0.5.8.1
  python:         /root/.local/share/r-miniconda/envs/r-omnideconv/bin/python
  libpython:      /root/.local/share/r-miniconda/envs/r-omnideconv/lib/libpython3.10.so
  pythonhome:     /root/.local/share/r-miniconda/envs/r-omnideconv:/root/.local/share/r-miniconda/envs/r-omnideconv
  version:        3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
  numpy:          /root/.local/share/r-miniconda/envs/r-omnideconv/lib/python3.10/site-packages/numpy
  numpy_version:  1.26.4

  NOTE: Python version was forced by use_python() function
  [1] "Method: cpm; sc-norm: ; bulk-norm: "
  Error in if (sc_norm == "counts") { : argument is of length zero
  Execution halted

Work dir:
  /home/sciliciumtheo/omnideconv_bench/work/86/d44564698550225faaf45fd95d86eb

Container:
  alexd13/omnideconv_benchmark:latest

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
```

For `bseqsc`, the only difference is:
```
  NOTE: Python version was forced by use_python() function
  [1] "Method: bseqsc; sc-norm: ; bulk-norm: "
  Error in if (sc_norm == "counts") { : argument is of length zero
  Execution halted
```

Best,
Theo

**Comment by alex-d13** [comment]
Hi,

Thanks for using deconvBench! I am currently reworking the Docker image, I already pushed a version 1.4, that you might try? Happy for Feedback!

Best,
Alex

**Comment by SciLiciumTheo** [comment]
Hi,

Thanks for the quick feedback!

I just pulled the 1.4 version, changed the docker profile in `nextflow.config` accordingly, but the problem is still present:

```
ERROR ~ Error executing process > 'CREATE_SIGNATURE (1)'

Caused by:
  Process `CREATE_SIGNATURE (1)` terminated with an error exit status (1)


Command executed:

  computeSignaturesNF.R 'sc1' '/home/sciliciumtheo/omnideconv_bench/data/single_cell/' 'bulk1' '/home/sciliciumtheo/omnideconv_bench/data/bulks/' 'cdseq' '/home/sciliciumtheo/omnideconv_bench/test_results_1.4' 'false' '0' '0' '4' '/home/sciliciumtheo/omnideconv_bench/pipeline'

Command exit status:
  1

Command output:
  [1] "Starting signature building script ..."
  R version 4.4.0 (2024-04-24)
  Platform: x86_64-pc-linux-gnu
  Running under: Ubuntu 20.04.6 LTS

  Matrix products: default
  BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
  LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3;  LAPACK version 3.9.0

  locale:
  [1] C

  time zone: Etc/UTC
  tzcode source: system (glibc)

  attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods   base

  other attached packages:
  [1] omnideconv_0.1.1  snowfall_1.84-6.3 snow_0.4-4

  loaded via a namespace (and not attached):
   [1] Matrix_1.7-0        gtable_0.3.6        jsonlite_1.9.1
   [4] dplyr_1.1.4         compiler_4.4.0      Rcpp_1.0.14
   [7] tidyselect_1.2.1    Biobase_2.62.0      parallel_4.4.0
  [10] tidyr_1.3.1         png_0.1-8           scales_1.3.0
  [13] fastmap_1.2.0       lattice_0.22-6      reticulate_1.42.0
  [16] ggplot2_3.5.1       R6_2.6.1            generics_0.1.3
  [19] BiocGenerics_0.48.1 htmlwidgets_1.6.4   tibble_3.2.1
  [22] munsell_0.5.1       pillar_1.10.1       RColorBrewer_1.1-3
  [25] rlang_1.1.5         lazyeval_0.2.2      viridisLite_0.4.2
  [28] plotly_4.10.4       cli_3.6.4           withr_3.0.2
  [31] magrittr_2.0.3      digest_0.6.37       grid_4.4.0
  [34] rappdirs_0.3.3      lifecycle_1.0.4     vctrs_0.6.5
  [37] glue_1.8.0          data.table_1.17.0   colorspace_2.1-1
  [40] purrr_1.0.4         httr_1.4.7          tools_4.4.0
  [43] pkgconfig_2.0.3     htmltools_0.5.8.1
  python:         /root/.local/share/r-miniconda/envs/r-omnideconv/bin/python
  libpython:      /root/.local/share/r-miniconda/envs/r-omnideconv/lib/libpython3.8.so
  pythonhome:     /root/.local/share/r-miniconda/envs/r-omnideconv:/root/.local/share/r-miniconda/envs/r-omnideconv
  version:        3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55)  [GCC 11.3.0]
  numpy:          /root/.local/share/r-miniconda/envs/r-omnideconv/lib/python3.8/site-packages/numpy
  numpy_version:  1.23.5

  NOTE: Python version was forced by use_python() function
  [1] "Method: cdseq; sc-norm: ; bulk-norm: "

Command error:
  Loading required package: snowfall
  Loading required package: snow
  Skipping python installation checks ...
  R version 4.4.0 (2024-04-24)
  Platform: x86_64-pc-linux-gnu
  Running under: Ubuntu 20.04.6 LTS

  Matrix products: default
  BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
  LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3;  LAPACK version 3.9.0

  locale:
  [1] C

  time zone: Etc/UTC
  tzcode source: system (glibc)

  attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods   base

  other attached packages:
  [1] omnideconv_0.1.1  snowfall_1.84-6.3 snow_0.4-4

  loaded via a namespace (and not attached):
   [1] Matrix_1.7-0        gtable_0.3.6        jsonlite_1.9.1
   [4] dplyr_1.1.4         compiler_4.4.0      Rcpp_1.0.14
   [7] tidyselect_1.2.1    Biobase_2.62.0      parallel_4.4.0
  [10] tidyr_1.3.1         png_0.1-8           scales_1.3.0
  [13] fastmap_1.2.0       lattice_0.22-6      reticulate_1.42.0
  [16] ggplot2_3.5.1       R6_2.6.1            generics_0.1.3
  [19] BiocGenerics_0.48.1 htmlwidgets_1.6.4   tibble_3.2.1
  [22] munsell_0.5.1       pillar_1.10.1       RColorBrewer_1.1-3
  [25] rlang_1.1.5         lazyeval_0.2.2      viridisLite_0.4.2
  [28] plotly_4.10.4       cli_3.6.4           withr_3.0.2
  [31] magrittr_2.0.3      digest_0.6.37       grid_4.4.0
  [34] rappdirs_0.3.3      lifecycle_1.0.4     vctrs_0.6.5
  [37] glue_1.8.0          data.table_1.17.0   colorspace_2.1-1
  [40] purrr_1.0.4         httr_1.4.7          tools_4.4.0
  [43] pkgconfig_2.0.3     htmltools_0.5.8.1
  python:         /root/.local/share/r-miniconda/envs/r-omnideconv/bin/python
  libpython:      /root/.local/share/r-miniconda/envs/r-omnideconv/lib/libpython3.8.so
  pythonhome:     /root/.local/share/r-miniconda/envs/r-omnideconv:/root/.local/share/r-miniconda/envs/r-omnideconv
  version:        3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55)  [GCC 11.3.0]
  numpy:          /root/.local/share/r-miniconda/envs/r-omnideconv/lib/python3.8/site-packages/numpy
  numpy_version:  1.23.5

  NOTE: Python version was forced by use_python() function
  [1] "Method: cdseq; sc-norm: ; bulk-norm: "
  Error in if (sc_norm == "counts") { : argument is of length zero
  Execution halted

Work dir:
  /home/sciliciumtheo/omnideconv_bench/work/1d/451d3a32c6358a4a0a55571454801b

Container:
  alexd13/omnideconv_benchmark:1.4

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```

**Comment by SciLiciumTheo** [comment]
Just to inform you, I am in the process of adding these methods to deconvBench.

`cpm` and `CDseq` already implemented, currently testing `momf`. 
I will probably finish at the beginning of next week.

**Comment by SciLiciumTheo** [comment]
`momf` just finished running smoothly.

Retrospectively, I don't think adding BSeq-SC is really worth it, for the following reasons:
1. this method needs a pre-defined set of marker genes, while other do not, and IMO this limits the scope of this tool;
2. it internally builds on CIBERSORT, which is a tool already supported;
3. the [GitHub repo](https://github.com/shenorrLabTRDF/bseqsc/) seems abandoned, no update in 8 years, broken links, issues mentioning broken links open without any response for years.

**Comment by alex-d13** [comment]
I totally agree, especially point 1) is a reason why we did not include it in our benchmark :)
